import { FakeData } from "~/app/(authenticated)/dashboard/request/columns";

export async function getData(): Promise<FakeData[]> {
	return [
		{
			id: "1",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "a@example.com",
			applied_date: "1021-01-01",
		},
		{
			id: "2",
			department: "Department of CIT-UC",
			status: "Panel Interview",
			applicant_name: "b@example.com",
			applied_date: "1314-01-01",
		},
		{
			id: "3",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "c@example.com",
			applied_date: "1241-01-01",
		},
		{
			id: "4",
			department: "Department of CIT-UC",
			status: "Panel Interview",
			applicant_name: "d@example.com",
			applied_date: "000-01-01",
		},
		{
			id: "5",
			department: "Department of CIT-UC",
			status: "Recommendation for Hiring",
			applicant_name: "e@example.com",
			applied_date: "232-01-01",
		},
		{
			id: "6",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "f@example.com",
			applied_date: "21-01-01",
		},
		{
			id: "7",
			department: "Department of CIT-UC",
			status: "Recommendation for Hiring",
			applicant_name: "g@example.com",
			applied_date: "3-01-01",
		},
		{
			id: "8",
			department: "Department of CIT-UC",
			status: "Psychological Exam",
			applicant_name: "h@example.com",
			applied_date: "2424525-01-01",
		},
		{
			id: "9",
			department: "Department of CIT-UC",
			status: "Psychological Exam",
			applicant_name: "i@example.com",
			applied_date: "2022-24-01",
		},
		{
			id: "10",
			department: "Department of CIT-UC",
			status: "Initial Interview",
			applicant_name: "j@example.com",
			applied_date: "2022-023231-01",
		},
		{
			id: "11",
			department: "Department of CIT-UC",
			status: "Psychological Exam",
			applicant_name: "k@example.com",
			applied_date: "24-234-01",
		},
		{
			id: "12",
			department: "Department of CIT-UC",
			status: "Teaching Demo",
			applicant_name: "l@example.com",
			applied_date: "23-242-01112",
		},
		{
			id: "13",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "m@example.com",
			applied_date: "01-20-2024",
		},
		{
			id: "14",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "n@example.com",
			applied_date: "232-01-01",
		},
		{
			id: "15",
			department: "Department of CIT-UC",
			status: "Initial Interview",
			applicant_name: "o@example.com",
			applied_date: "09-01-01",
		},
		{
			id: "16",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "p@example.com",
			applied_date: "24242-01-01",
		},
		{
			id: "17",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "q@example.com",
			applied_date: "23255-01-01",
		},
		{
			id: "18",
			department: "Department of CIT-UC",
			status: "Initial Interview",
			applicant_name: "r@example.com",
			applied_date: "6767-01-01",
		},
		{
			id: "19",
			department: "Department of CIT-UC",
			status: "Screening",
			applicant_name: "s@example.com",
			applied_date: "7878-01-01",
		},
		{
			id: "20",
			department: "Department of CIT-UC",
			status: "Teaching Demo",
			applicant_name: "t@example.com",
			applied_date: "9999-9999-9999",
		},
		{
			id: "21",
			department: "Department of CIT-UC",
			status: "Teaching Demo",
			applicant_name: "tawd@example.com",
			applied_date: "729-9999",
		},
		{
			id: "22",
			department: "Department of CIT-UC",
			status: "Teaching Demo",
			applicant_name: "tawds@example.com",
			applied_date: "9999",
		},
	];
}
