import { FakeApplicantData } from "~/app/(authenticated)/dashboard/applicant/columns";

export async function getApplicantData(): Promise<FakeApplicantData[]> {
	return [
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "a@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "1021-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "b@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Panel Interview",
			applied_date: "1314-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "c@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "1241-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "d@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Panel Interview",
			applied_date: "000-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "e@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Recommendation for Hiring",
			applied_date: "232-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "f@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "21-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "g@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Recommendation for Hiring",
			applied_date: "3-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "h@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Psychological Exam",
			applied_date: "2424525-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "i@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Psychological Exam",
			applied_date: "2022-24-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "j@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Initial Interview",
			applied_date: "2022-023231-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "k@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Psychological Exam",
			applied_date: "24-234-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "l@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Teaching Demo",
			applied_date: "23-242-01112",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "m@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "01-20-2024",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "n@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "232-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "o@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Initial Interview",
			applied_date: "09-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "p@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "24242-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "q@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "23255-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "r@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Initial Interview",
			applied_date: "6767-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "s@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Screening",
			applied_date: "7878-01-01",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "t@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Teaching Demo",
			applied_date: "9999-9999-9999",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "tawd@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Teaching Demo",
			applied_date: "729-9999",
		},
		{
			applicant_id: "applicant_id of CIT-UC",
			applicant_name: "tawds@example.com",
			position: "IT/CS Faculty",
			department: "College of Computer Studies",
			status: "Teaching Demo",
			applied_date: "9999",
		},
	];
}
