export const cultureAddQuestions = {
	cultureOfExcellence: [
		"How do you see your personal values and work ethic aligning with the company culture, and how do you plan to embody these values in your work?",
		"Can you describe a time when you took initiative to create a positive impact on your team or the company, and what motivated you to take that action?",
		"What is your approach to utilizing data and metrics to make informed decisions in your work, and can you describe a specific example of how you have successfully used data to improve a process or outcome?",
		"How do you approach building and maintaining strong relationships with clients and colleagues, and can you describe a time when you demonstrated empathy and understanding in a challenging situation?",
		"How do you balance the need for quality work with the need to meet deadlines, and can you describe a time when you had to make trade-offs between the two? How did you communicate with stakeholders and manage expectations?",
		"Can you describe a time when you took the initiative to learn and develop new skills, and how did you apply them to improve your work or the work of your team?",
		"How do you approach solving complex problems and making difficult decisions in your work, and can you give an example of how you have successfully navigated a challenging situation?",
		"Can you describe a time when you took ownership of a project or task, and how did you communicate progress and collaborate with others to achieve success?",
		"What drives you to continuously learn and grow in your work, and can you describe a time when you incorporated feedback to improve your performance and contribute to the success of the team?",
		"How do you prioritize tasks and manage competing demands in your work, and can you give an example of how you have effectively managed multiple projects or assignments simultaneously?",
		"Can you tell us about a time when you took the initiative to improve your own professional development and how it contributed to the team's success?",
		"How do you balance competing priorities to ensure that you meet deadlines while also delivering high-quality work?",
		"Can you describe a situation where you took personal responsibility for a mistake or error you made and what steps you took to prevent it from happening again?",
		"How do you define and measure success in your work, and how do you adjust your approach if you're not meeting your goals?",
		"Can you share an example of how you manage competing priorities and deadlines while still delivering excellent results?",
		"Can you provide an example of a project or task where you took the lead and the positive impact it had on the team and/or organization?",
		"How do you approach feedback and criticism of your work, and can you share a specific example of how you used feedback to improve your performance?",
		"Can you describe a situation where you had to make a difficult decision and how you balanced competing needs to arrive at the best outcome?",
		"What motivates you to stay on track with your work and meet deadlines, and how do you ensure that you remain focused and productive?",
		"Can you share an example of how you exceeded a client's expectations by incorporating innovative ideas or creative solutions, and what impact it had on the project or the client's satisfaction?",
		"In what ways do you foster creativity and innovation in your problem-solving and decision-making? Can you provide an example of a unique and effective solution you developed to solve a complex problem in your previous work experience?",
		"Can you describe a time when you approached a project or task with an unconventional perspective, and how did your unique solution contribute to the project's success?",
		"How do you stay informed about emerging trends and new developments in your industry? Can you give an example of how you implemented a new idea or trend into your work to drive positive results?",
		"Can you tell us about a time when you received feedback that challenged your perspective or approach to a problem? How did you respond, and what did you learn from the experience?",
		"How do you foster a culture of creativity and innovation in your team or workplace? Can you provide an example of a successful team project where creative thinking played a critical role in achieving its goals?",
		"How do you balance the need for creativity and originality with the need for practicality and efficiency in your work?",
		"Can you describe a time when you took a calculated risk or implemented a new idea in your work? What was the outcome, and what did you learn from the experience?",
		"How do you handle situations where you face a roadblock or obstacle in your work? Can you give an example of how you overcame it by applying creative thinking and problem-solving skills?",
		"Can you share an example of a project or task where you collaborated with others to generate creative ideas and solutions? How did you facilitate the creative process, and what was the result?",
		"How do you measure the impact and success of your creative ideas and solutions? Can you provide an example of a project or initiative that you led, which had a positive impact on your organization or customers, and how did you measure its success?",
		"How do you balance long-term and short-term goals to prioritize tasks and ensure timely completion of projects and deliverables?",
		"Can you describe a time when you had to manage multiple tasks and projects simultaneously while maintaining high-quality work and meeting tight deadlines? How did you approach it?",
		"How do you manage interruptions or urgent requests while maintaining productivity and ensuring timely delivery of your work?",
		"Can you tell us about a time when you had to communicate with stakeholders or team members to ensure timely delivery of a project? What steps did you take to follow up and ensure everyone was on track?",
		"How do you handle shifting priorities or conflicting demands on your time? Can you give an example of how you reprioritized your tasks to meet a deadline?",
		"Can you describe a time when you identified a potential delay in a project and took proactive steps to prevent it from impacting the timeline?",
		"How do you keep track of deadlines and manage your workload to avoid missing important tasks or deliverables?",
		"Can you provide an example of how you adapted to unexpected changes in project timelines or shifting priorities without compromising on the quality of your work?",
		"How do you prioritize tasks and manage your workload when working on multiple projects or dealing with competing deadlines?",
		"Can you share an example of how you improved the efficiency of a process or workflow to increase productivity and meet deadlines?",
		"How do you find motivation to consistently perform at a high level in your work? Can you share an example of a time when you went above and beyond your job responsibilities?",
		"Can you describe a situation where your positive attitude and energy had a significant impact on a project or team? How did you maintain that level of enthusiasm?",
		"How do you stay resilient and maintain a positive outlook when faced with setbacks or challenges in your work?",
		"How do you approach new tasks or projects with a willingness to learn and grow? Can you share an example of how you overcame a learning curve in a new role or project?",
		"How do you create a positive and collaborative work environment that fosters enthusiasm and energy among your colleagues or team members?",
		"Can you give an example of a time when you took the initiative to take on additional responsibilities or a new project with enthusiasm and energy? How did you balance these new tasks with your existing workload?",
		"How do you stay focused and motivated when faced with repetitive or monotonous tasks in your work?",
		"Can you share an example of how you have built and maintained positive relationships with clients or stakeholders through your enthusiasm and energy?",
		"How do you channel your enthusiasm and energy in a constructive way when faced with unexpected changes or challenges in your work? Can you give an example of how you adapted to a difficult situation with a positive attitude?",
		"How do you ensure that you maintain a healthy work-life balance while still bringing enthusiasm and energy to your work? Can you describe how you manage your time and prioritize self-care activities?",
		"How do you ensure that quality is a top priority in your work, even when facing time constraints or pressure to deliver results quickly?",
		"Can you give an example of a time when you took extra steps to ensure a project or task was completed with the highest level of accuracy and precision possible?",
		"How do you approach tasks that require a high degree of attention to detail and precision? What strategies do you use to ensure accuracy?",
		"Can you tell us about a time when you discovered an error or mistake in your work and took steps to resolve it before it became a significant issue?",
		"How do you manage your time and workload to ensure that you meet deadlines while still maintaining a high level of quality in your work?",
		"How do you stay focused and motivated when working on long-term or complex projects that require a high level of diligence and attention to detail?",
		"Can you describe a time when you successfully managed multiple projects simultaneously while maintaining a high level of diligence and attention to detail in each one?",
		"How do you approach challenges or setbacks in your work, and how do you stay motivated to continue working with diligence and attention to detail?",
		"Can you share an example of a time when you proactively sought out opportunities to improve the quality or accuracy of your work and made changes to achieve that goal?",
		"How do you balance the need for diligence and attention to detail with the need for flexibility and adaptability in a fast-paced work environment?",
	],
	integrity: [
		"At our university, we prioritize integrity and ethical principles in the workplace. How do you define integrity, and can you give some examples of how you uphold ethical principles in your work?",
		"In your experience, can you describe a challenging ethical dilemma you faced in your previous job? How did you approach the situation, and what actions did you take to resolve it?",
		"In the workplace, conflicts of interest may arise where personal and professional interests conflict. How do you handle such situations, and what steps do you take to ensure that you remain impartial?",
		"Honesty and transparency are essential in the workplace. Can you give an example of a time when you had to deliver a difficult message to a coworker or supervisor? How did you approach the situation?",
		"Confidentiality is critical in many roles at our university. Can you describe a situation where you had to handle confidential information? How did you ensure that it was kept confidential?",
		"Taking responsibility for one's mistakes is an essential aspect of professional integrity. Can you describe a situation where you made a mistake and had to take responsibility for it? How did you communicate it to your team or supervisor, and what steps did you take to address it?",
		"Our university operates under strict legal and regulatory requirements. How do you ensure that your work meets these requirements and that you remain compliant with applicable laws and regulations?",
		"Sometimes standing up for what is right may be unpopular or go against the norm. Can you describe a situation where you had to take a stand for what you believed in, even if it was unpopular?",
		"At our university, we expect our employees to maintain high ethical standards both at work and in their personal lives. Can you describe how you maintain a high level of ethical conduct in your personal life outside of work?",
		"Courage and integrity are essential qualities in the workplace. Can you give an example of a time when you demonstrated these qualities in the face of pressure or adversity?",
		"Can you tell me about a time when you made a mistake at work? How did you handle it, and what did you learn from the experience?",
		"How do you ensure that your actions and words align with your personal values and beliefs, while also meeting the expectations and values of your employer?",
		"How do you handle situations where your personal values conflict with the values of your employer or colleagues, while maintaining a positive work relationship?",
		"Can you give an example of a time when you had to make a difficult ethical decision at work? How did you approach the situation, and what was the outcome?",
		"In what ways do you actively seek feedback on your performance and areas for improvement, while also giving feedback to others?",
		"How do you handle situations where you may not know the answer or need to ask for help, while also maintaining a sense of confidence and competence in your role?",
		"Can you describe a time when you had to give constructive feedback to a colleague or supervisor? How did you approach the situation, and what was the outcome?",
		"How do you handle situations where you witness unethical or illegal behavior in the workplace, while also ensuring that you do not compromise your own professional reputation or relationship with others?",
		"Can you describe a time when you stood up for what you believed was right, even when it was difficult or unpopular? How did you handle any pushback or resistance?",
		"In what ways do you hold yourself accountable for your actions and decisions in the workplace, while also encouraging accountability in others?",
		"How do you balance being available to your colleagues and clients while also prioritizing your own workload and responsibilities?",
		"Can you describe a time when you had to adjust your availability to accommodate the needs of a colleague or client?",
		"How do you ensure that you are able to effectively communicate with colleagues and clients who may have different communication preferences or needs?",
		"Can you share an example of a time when you had to renegotiate a commitment or deadline with a colleague or client? How did you approach the situation?",
		"How do you ensure that you are able to meet the needs and expectations of your clients and colleagues while also maintaining your own boundaries and limitations?",
		"Can you describe a time when you had to learn a new skill or acquire new knowledge in order to better serve your clients or colleagues?",
		"How do you foster a culture of collaboration and teamwork within your department or organization?",
		"Can you share an example of a time when you had to rebuild trust with a colleague or client after a breakdown in communication or a mistake was made?",
		"How do you communicate difficult decisions or news to clients or colleagues in a way that is respectful and empathetic?",
		"Can you describe a time when you had to navigate a difficult conflict or disagreement with a colleague or client? How did you approach the situation?",
		"Can you share an example of a time when you had to balance the need for confidentiality with the need for transparency in the workplace?",
		"Have you ever faced a situation where the ethical principles of your employer or colleagues conflicted with your personal values or beliefs? How did you handle it?",
		"Can you describe a time when you had to prioritize competing demands and balance your workload to ensure that you met your commitments and deadlines?",
		"How do you handle situations where your personal or professional interests conflict with those of your colleagues or clients?",
		"Can you share an example of a time when you had to navigate a difficult conversation with a colleague or supervisor regarding unethical behavior in the workplace?",
		"How do you handle situations where you need to learn a new skill or gain knowledge to complete a project or task?",
		"Can you describe your approach to managing your time and workload to ensure that you are productive and efficient while meeting deadlines?",
		"How do you approach mistakes or errors in your work, and what steps do you take to address them?",
		"Can you describe a time when you had to work with someone who initially did not trust you or doubted your abilities? How did you build trust with them?",
		"How do you ensure that you are communicating effectively and transparently with colleagues and clients, especially in high-pressure situations?",
		"Can you describe a specific example of when you had to make a difficult decision that required you to weigh competing ethical considerations? How did you approach the situation?",
		"How do you ensure that you act with integrity in all aspects of your work, even when it may be difficult or inconvenient?",
		"Can you provide an example of a time when you observed a colleague engaging in behavior that may have violated ethical standards? How did you address the situation?",
		"How do you handle situations where there is a conflict between your personal values and the values of your organization or supervisor?",
		"How do you stay informed about changes and updates to ethical standards in your field or industry?",
		"Can you describe a situation where you had to make an ethical decision in a time-sensitive or high-pressure environment? How did you approach the situation?",
		"How do you build a culture of ethical behavior within your team or organization?",
		"Can you describe a time when you had to address an ethical dilemma that had potential legal implications?",
		"How do you incorporate diverse perspectives and cultural considerations into your ethical decision-making process?",
		"Can you describe a time when you had to weigh the ethical implications of a decision against its potential impact on business or organizational goals?",
		"How do you prioritize your work tasks to ensure that you can contribute to achieving the University's goals and objectives?",
		"Can you tell us about a time when you were presented with a challenging project or task that required you to learn new skills or take on additional responsibilities? How did you approach the situation, and what was the outcome?",
		"How do you manage your time effectively to ensure that you are productive and achieve your work targets, even when faced with distractions or competing demands?",
		"Have you ever had a disagreement with a colleague or supervisor regarding the best approach to completing a task or project? How did you handle the situation, and what was the outcome?",
		"Can you provide an example of how you have consistently produced high-quality work over time, and how do you ensure that you maintain this standard?",
		"How do you handle situations where there is a miscommunication or a lack of clarity regarding your work responsibilities or goals? What steps do you take to resolve these issues?",
		"Can you describe how you ensure that your work complies with the University's policies, regulations, and ethical standards?",
		"How do you stay informed of changes or updates to work procedures, regulations, or policies, and how do you integrate this new information into your work?",
		"Can you tell us about a time when you made a mistake at work and had to take corrective action? How did you handle the situation, and what did you learn from it?",
		"How do you take ownership of your work responsibilities, and how do you demonstrate initiative and proactivity in completing your tasks to the best of your abilities?",
	],
	teamwork: [
		"Can you describe a situation where you had to collaborate with others outside of your team or department to achieve a goal? How did you ensure effective communication and coordination to accomplish the task?",
		"How do you approach giving feedback to a supervisor or someone in a higher position of authority? Can you describe a situation where you had to provide constructive feedback to a superior, and how you handled the conversation?",
		"Can you describe a time when you had to work with someone who had a different cultural background or perspective from your own? How did you ensure cultural sensitivity and effective communication in the work relationship?",
		"How do you approach managing conflict between team members who have different opinions or approaches to work? Can you provide an example of a time when you successfully resolved a conflict within a team?",
		"Can you describe a time when you had to lead a team through a challenging or high-pressure situation, and how you motivated and supported your team to achieve success?",
		"How do you ensure that all team members have an opportunity to contribute their ideas and opinions, especially in situations where some may be more reserved or hesitant to speak up?",
		"Can you describe a situation where you had to provide constructive criticism or feedback to a team member who was not meeting expectations or delivering quality work?",
		"How do you approach creating a sense of shared accountability and responsibility within a team to ensure that everyone is working toward the same goals and objectives?",
		"Can you describe a time when you had to manage a difficult team member or address a team dynamic issue that was affecting productivity or morale?",
		"How do you ensure that all team members feel valued and recognized for their contributions, especially in situations where some may be less vocal or outgoing than others?",
		"Can you describe a specific team project that you were a part of in the past and your role in it? How did you contribute to the team's success?",
		"Can you give an example of a time when you had to resolve a conflict within a team? How did you approach the situation and what steps did you take to resolve the conflict?",
		"How do you balance individual goals with team goals when working on a project or task? Can you give an example of how you have managed to do this in the past?",
		"Can you describe how you have contributed to a positive team culture in the past? What specific actions did you take to help foster a positive work environment?",
		"Can you provide an example of a situation where you had to compromise your personal preferences or goals for the benefit of the team? How did you approach the situation?",
		"How do you ensure that communication within a team is effective and everyone is on the same page? Can you give an example of a time when you had to improve communication within a team?",
		"How do you address team members who are not contributing or pulling their weight? Can you give an example of how you have dealt with such a situation in the past?",
		"Can you tell me about a time when you had to adapt your work style to fit within a team's working style? How did you approach the situation and what steps did you take to adapt?",
		"How do you build relationships and trust with your team members? Can you give an example of how you have built strong relationships with your teammates?",
		"How do you measure the success of a team effort? What metrics or indicators do you use to evaluate the team's success?",
		"Can you describe a time when you had to have a difficult conversation with a coworker or team member? How did you approach the conversation, and what was the outcome?",
		"What is your preferred method of communication with team members, and how do you ensure effective communication in the workplace? Can you give an example of a time when your communication style positively impacted a team project or goal?",
		"Have you ever received constructive criticism or feedback from a team member that was difficult to hear? How did you respond to the feedback, and what actions did you take to address it?",
		"Can you describe a situation where you had to work with a colleague whom you didn't initially get along with? How did you overcome any differences or challenges to successfully work together?",
		"How do you build and maintain positive relationships with colleagues and team members? Can you provide an example of a successful collaboration or project that you worked on with a colleague?",
		"How do you handle conflicts or disagreements with team members, and what steps do you take to resolve them? Can you provide an example of how you successfully resolved a conflict in the workplace?",
		"How do you ensure inclusivity and respect towards colleagues with diverse backgrounds and perspectives? Can you describe a time when you actively demonstrated respect and inclusivity towards a colleague or team member?",
		"How do you adjust your communication style to accommodate team members with different communication preferences or styles? Can you provide an example of how you successfully communicated with a team member with a different communication style?",
		"Can you describe a time when you went out of your way to help a colleague or mentor a new team member? What actions did you take, and what was the outcome?",
		"How do you balance your own work responsibilities with supporting team members who need help or guidance? Can you provide an example of a time when you effectively balanced your own workload with supporting a team member?",
		"Can you describe a time when you took the initiative to mentor or coach a coworker, and how it contributed to their success?",
		"How do you approach collaboration and teamwork with colleagues who may have different communication styles or work preferences?",
		"Can you give an example of how you have shown flexibility and adaptability in a work situation to better support a colleague or team?",
		"How do you actively work to create a culture of respect, appreciation, and support within your team and the broader organization?",
		"Can you describe a time when you took a leadership role in promoting diversity and inclusion in the workplace, and how it positively impacted your team or organization?",
		"How do you balance the need to be supportive of your colleagues with the need to hold them accountable for their work and responsibilities?",
		"Can you provide an example of how you have effectively resolved a conflict or disagreement with a colleague while maintaining a positive and respectful relationship?",
		"How do you approach teamwork and collaboration with colleagues who have different levels of experience or skillsets?",
		"Can you describe a time when you had to provide feedback to a colleague, and how you ensured it was constructive and helpful to their professional growth?",
		"How do you actively seek out opportunities to recognize and celebrate the accomplishments of your colleagues and team members?",
		"Can you describe a time when you worked on a project where collaboration was essential to its success? How did you contribute to the collaborative effort?",
		"How do you create a culture of open feedback and discussion when presenting your ideas to a team? Can you give an example of how you have encouraged team members to share their thoughts and opinions?",
		"Have you ever had to compromise your ideas in order to work collaboratively with others? Can you provide an example of how you approached this situation and ensured the success of the project?",
		"How do you handle conflicts that arise during collaborative projects? Can you give an example of how you resolved a conflict while still maintaining positive relationships with your colleagues?",
		"Have you ever worked with someone who had a different work style or personality than yours? How did you adjust your approach to work collaboratively with them? Can you provide an example of how this collaboration was successful?",
		"Can you describe a situation where you helped a team member improve their work or overcome a challenge while working on a collaborative project? How did you approach this situation and what was the outcome?",
		"How do you ensure that all team members feel heard and valued during group discussions while collaborating on a project? Can you provide an example of how you have created an inclusive environment for team members to share their ideas?",
		"How do you handle disagreements or differences of opinion when collaborating on a project? Can you give an example of how you navigated a conflict while still achieving the project's objectives?",
		"Can you describe a project where you were not the team leader, but still played an important role in its success through collaboration with others? What was your role and how did you contribute to the project's success?",
		"How do you balance your individual responsibilities with those of the team when collaborating on a project? Can you give an example of how you managed your workload while still ensuring the success of the project as a whole?",
		"How do you balance competing priorities and stay focused on the most important tasks, while ensuring that you meet all deadlines?",
		"Can you share an example of a time when you took initiative to go above and beyond what was expected of you in order to achieve a project or task?",
		"What strategies do you use to stay motivated and overcome challenges when working on a difficult task or project?",
		"Can you describe a time when you had to adjust your organizational methods to better meet the needs of your team or colleagues?",
		"How do you approach decision-making when faced with difficult choices that could potentially impact your team or colleagues?",
		"What steps do you take to continuously improve your skills and knowledge in your field, and how have you applied this learning to your work?",
		"How do you manage your time effectively to ensure that you are meeting your commitments and avoiding burnout?",
		"Can you give an example of how you collaborated with others to achieve a project or task, and how you contributed to the success of the team?",
		"How do you ensure that you are keeping all team members informed and engaged in the progress of a project, particularly when working remotely or in a distributed team?",
		"Can you describe a time when you had to make sacrifices or adjustments to your personal life in order to meet your commitments to your team or colleagues?",
	],
	universality: [
		"Can you share an experience where you actively promoted diversity and inclusivity in the workplace or in your personal life?",
		"How do you ensure that your work considers the needs and perspectives of all stakeholders, including those who may be marginalized or underrepresented? Can you provide an example?",
		"Can you describe a time when you had to make a decision that was in the best interest of the greater good, even if it meant personal sacrifice?",
		"How do you integrate sustainability and environmental responsibility into your work or personal life? Can you provide an example?",
		"Have you ever worked with individuals from diverse cultural backgrounds? Can you describe a situation where you navigated potential conflicts or misunderstandings?",
		"How do you approach social responsibility in your work or personal life, and how do you ensure that your actions align with your values? Can you provide an example?",
		"Can you describe a time when you made a decision that took into account the long-term impact on the community or environment, rather than short-term gain? How did you approach this decision-making process?",
		"How do you practice ethical consumerism and responsible consumption in your personal life? Can you give an example?",
		"Can you share an experience where you stood up for the rights of others or challenged unjust systems or practices?",
		"How do you approach working with individuals who have different opinions or beliefs from your own, while ensuring that all voices are heard and respected in decision-making processes? Can you provide an example?",
		"How do you see yourself embracing the values and culture of CIT University and contributing to its success?",
		"How do you ensure that your personal goals are aligned with the strategic objectives of CIT University and that your work is aligned with the institution's mission and vision?",
		"Can you describe a time when you put the needs and objectives of your team or department ahead of your personal interests or goals, and how did this contribute to the overall success of your organization?",
		"How do you keep up to date with the latest initiatives and goals of CIT University, and how do you integrate this information into your work?",
		"Can you give an example of a time when you had to make a tough decision that conflicted with your personal preferences but was necessary to achieve the objectives of the institution?",
		"How do you strike a balance between the needs of your department or team and the broader goals and vision of CIT University?",
		"How do you ensure that your work is consistent with the core values and principles of CIT University?",
		"How do you measure the success of your work in terms of achieving the overall goals and vision of the institution?",
		"How do you maintain your motivation and dedication to the long-term goals of CIT University, even in the face of difficulties or setbacks?",
		"What are some specific ways in which you plan to contribute to the growth and success of CIT University in your new role, and how do these align with the institution's mission and vision?",
		"In what ways do you foster relationships with colleagues and clients, especially those with diverse backgrounds and perspectives?",
		"How do you ensure that your personal values align with the values and mission of the organization you work for, and how do you incorporate these values into your work?",
		"How do you plan to contribute to and enhance the culture of CIT University, and what past experiences demonstrate your ability to contribute to organizational culture?",
		"How do you handle situations where your departmental goals may conflict with the overall goals of the organization, and what strategies have you found to be effective in managing these conflicts?",
		"Can you describe a time when you had to make a difficult ethical decision, and what steps did you take to arrive at a resolution that aligned with the values and mission of the organization?",
		"In what ways do you stay informed about industry trends and changes, and how do you think this knowledge can benefit CIT University?",
		"How do you approach conflicts with colleagues or superiors, and what strategies have you found to be effective in resolving these conflicts while upholding organizational values?",
		"Can you describe a time when you had to take a stance on a controversial issue or make an unpopular decision that aligned with the values and mission of the organization?",
		"How do you prioritize your workload and manage competing demands to ensure that you are meeting the needs of both your team and the organization as a whole?",
		"How do you approach professional development and growth, and in what ways do you think this contributes to your ability to support and uphold the values and mission of CIT University?",
		"How do you see your personal values and beliefs aligning with the values and mission of the organization and the community, and how does this motivate you to participate in activities within them?",
		"How do you stay up-to-date on the latest developments and trends in your field, and how do you incorporate this knowledge into your work within the organization and community?",
		"Have you ever taken the initiative to lead or organize an event or project that promotes the organization's values or benefits the community? Can you share an example of such an initiative and its impact?",
		"In what ways have you contributed to creating a positive and inclusive work environment in your previous roles, and how would you bring this experience to CIT University?",
		"How do you balance your job responsibilities and participation in the activities of the organization and community, and what strategies do you use to manage your workload effectively?",
		"What unique skills, experiences, or knowledge do you possess that would make you an asset to the initiatives or programs of the organization, and how would you use these to contribute to the growth and success of CIT University?",
		"How do you prioritize and manage your time effectively to ensure that you fulfill your job responsibilities while also participating in the activities of the organization and community? Can you give an example of a time when you had to manage multiple responsibilities effectively?",
		"Can you describe a time when you faced a challenge while participating in a University or community activity, and how did you overcome it while remaining aligned with the organization's values and mission?",
		"In what ways do you believe that participating in the activities of the organization and community can contribute to your personal and professional growth, and how do you plan to leverage these opportunities?",
		"How would you contribute to creating a more inclusive and diverse community within the organization and the broader community, and what steps would you take to promote a culture of diversity and inclusion at CIT University?",
		"How do you approach making decisions that may impact your colleagues, projects, or the overall organization?",
		"How do you ensure that your work is aligned with the values, mission, and goals of the organization?",
		"Can you describe a time when you demonstrated an understanding of how your role impacts other members of the organization, and how did you use that understanding to improve your work or the work of others?",
		"How do you stay informed about changes in policies, procedures, or regulations that may affect your work or that of your team, and how do you ensure that you and your team comply with these changes?",
		"How do you identify and address potential risks or challenges that may arise in your work, and what steps do you take to mitigate those risks?",
		"Can you describe a time when you had to adapt to changes in the work environment or procedures to ensure that your work continued to meet the needs of the organization?",
		"How do you approach reporting mistakes or issues in your work or that of your team, and what steps do you take to ensure that they are resolved quickly and efficiently?",
		"Can you give an example of a difficult decision you had to make where you had to balance the needs of the organization and your personal values or beliefs, and how did you approach this situation?",
		"How do you handle conflicts with co-workers or team members, and what strategies have you found to be effective in resolving conflicts in a positive and constructive manner?",
		"Can you describe a time when you implemented feedback or suggestions from co-workers, supervisors, or customers to improve your work or that of the organization, and what was the outcome of that implementation?",
		"How do you stay informed about the latest policies and procedures in your field or industry, and what steps do you take to ensure that you are up-to-date with the latest developments in your organization?",
		"Can you describe a time when you had to balance your personal beliefs or values with the need to comply with a new policy or regulation in your organization?",
		"How do you manage your time and workload to ensure that you meet the commitments you have made to your team and organization, and what strategies have you found to be most effective in prioritizing tasks?",
		"Can you describe a time when you took extra steps or went above and beyond your job responsibilities to ensure the success of a project or task, and what was the outcome?",
		"How do you adapt to unexpected changes in your workload or responsibilities, and what strategies have you found to be most effective in managing stress during these times?",
		"Can you describe a situation where you had to work with a difficult coworker or team member, and how did you handle the situation to ensure that the project or task was completed successfully?",
		"How do you prioritize and manage multiple tasks or projects simultaneously, and what tools or techniques do you use to ensure that you meet your deadlines and commitments?",
		"Can you describe a time when you received constructive criticism or feedback on your work, and how did you use this feedback to improve your performance?",
		"Can you give an example of how you have taken the initiative to improve a process or project in your previous work experience, and what was the impact of your actions?",
		"How do you maintain a positive attitude and work ethic, even during challenging or stressful times, and what strategies have you found to be most effective in managing your emotions and maintaining your focus?",
	],
};
