export const jobfitQuestions = {
	experienceQuestions: [
		"Can you describe a project you worked on in your previous job that required similar skills as this position? What was your role in that project?",
		"How have you handled a difficult or challenging situation related to your previous work experience that is relevant to this position?",
		"What experience do you have with (specific skill required for the job) and how have you used it in a previous job?",
		"Can you tell me about a time when you went above and beyond your job responsibilities to achieve a goal or complete a project that is relevant to this position?",
		"What was your most significant achievement in your previous job that is relevant to this position, and how did you accomplish it?",
		"How have you contributed to the success of your previous team or department, and how does that relate to the responsibilities of this position?",
		"What experience do you have with (specific software or tool required for the job) and how have you used it in a previous job?",
		"Can you tell me about a time when you identified an opportunity to improve a process or system at your previous job that is relevant to this position?",
		"How have you developed and maintained relationships with customers or clients in your previous job that is relevant to this position?",
		"Can you provide an example of how you have managed competing priorities and deadlines in your previous job that is relevant to the responsibilities of this position?",
		"How does your experience align with the requirements of this role?",
		"Can you discuss a past role that had similar responsibilities to this position?",
		"How do you think your experience will allow you to make an immediate impact in this role?",
		"Can you discuss how you have adapted your experience to fit different roles in the past?",
		"Can you describe how you have incorporated feedback from previous roles to improve your work?",
		"What is the broadest range of tasks you have handled in your previous role?",
		"Can you discuss a time when you had to work outside of your area of expertise?",
		"How have you expanded your skillset in previous roles?",
		"Can you discuss how you have adapted to changing responsibilities or priorities in the past?",
		"How do you ensure that you stay knowledgeable about the different aspects of your field?",
		"Can you describe a time when you had to resolve a complex issue related to your job?",
		"How have you developed your expertise in your field?",
		"Can you discuss a time when you had to make a difficult decision in your previous role?",
		"Can you describe how you have taken a deep dive into a specific project or area of expertise?",
		"Can you discuss how you have developed your skills in your previous roles?",
		"Can you discuss a project you completed that had a significant impact on the organization?",
		"Can you describe a time when you achieved a difficult goal in your previous role?",
		"Can you discuss a time when you had to work under pressure to complete a project?",
		"Can you describe how you have made a meaningful contribution to your previous team?",
		"Can you discuss how you have been recognized for your accomplishments in your previous roles?",
		"Can you discuss how you have applied skills learned in a previous job to a new role?",
		"How have you developed your transferable skills in your previous roles?",
		"Can you describe how you have leveraged your transferable skills to bring value to your previous organization?",
		"Can you discuss a time when you applied a transferable skill to a new situation?",
		"How do you identify and develop transferable skills in yourself and others?",
		"Can you describe a time when you had to navigate a difficult work relationship?",
		"Can you discuss a time when you had to handle a crisis situation at work?",
		"Can you describe a time when you had to overcome a lack of resources to complete a project?",
		"Can you discuss a time when you had to manage a team through a challenging project or situation?",
		"How do you approach difficult decisions or situations in the workplace?",
		"Can you describe a time when you had to manage a team through a challenging project?",
		"Can you discuss how you have developed leadership skills in previous roles?",
		"How have you motivated and inspired your team in previous roles?",
		"Can you describe how you have handled a conflict within a team?",
		"How do you approach delegation and giving feedback to team members?",
		"Can you describe a time when you pursued professional development outside of your job responsibilities?",
		"How do you stay current with developments in your field?",
		"Can you discuss how you have incorporated feedback from previous roles to improve your skills?",
		"How do you identify areas for growth and development in your work?",
		"Can you describe how you have taken on new responsibilities to expand your skillset?",
		"Can you provide contact information for previous managers or colleagues who can speak to your experience and work ethic?",
		"How have you built and maintained positive relationships with previous colleagues and supervisors?",
		"How have previous managers or colleagues evaluated your work and contributions?",
		"Can you describe a situation where you received positive feedback from a supervisor or coworker?",
		"How have you handled a situation where you received negative feedback from a supervisor or coworker?",
		"Can you describe how you see yourself growing in this position?",
		"How do you approach professional development and growth opportunities?",
		"Can you provide examples of how you have taken on new challenges and responsibilities to expand your skills and knowledge?",
		"Can you discuss a time when you pursued learning and development opportunities outside of your job responsibilities?",
		"How have you adapted and grown in previous job roles to take on more responsibilities or leadership positions?",
	],
	competenceQuestions: [
		"Can you describe a technical challenge you faced in your previous job and how you overcame it?",
		"How do you stay up-to-date with industry trends and advancements in your field?",
		"How do you prioritize your tasks and manage your time to meet deadlines?",
		"Can you give an example of how you have applied your technical knowledge to improve a process or project?",
		"How do you handle complex problem-solving situations in your work?",
		"How do you balance attention to detail with speed and efficiency in your work?",
		"Can you describe a time when you had to adapt to a new technology or system and how you managed the transition?",
		"How do you approach learning new technical skills or tools?",
		"Can you give an example of a project or task that you completed successfully using your technical skills?",
		"How do you ensure quality in your work and prevent errors or mistakes from occurring?",
		"What technical skills have you acquired in your previous work experiences that would be useful for this role?",
		"Can you describe a particularly technical project that you have worked on in the past?",
		"Have you ever had to learn a new technical skill quickly? Can you walk me through that experience?",
		"How do you stay up to date with industry changes and advancements in your field?",
		"Can you give an example of a time when you used your technical skills to solve a problem in a creative way?",
		"Can you describe a time when you solved a complex problem using data analysis?",
		"What is your process for approaching and solving problems?",
		"Can you walk me through how you would tackle a hypothetical problem in this role?",
		"Can you give an example of a time when you had to make a difficult decision with incomplete information?",
		"Can you describe a situation where you identified a problem and implemented a solution?",
		"Can you give an example of how you have effectively communicated with someone who has a different communication style than you?",
		"How do you tailor your communication to different audiences?",
		"Can you walk me through a time when you had to communicate bad news to a team or a customer?",
		"How do you handle conflicts or misunderstandings with colleagues or superiors?",
		"Can you give an example of a time when you had to deliver a presentation or report to a group?",
		"Can you describe your leadership style and how it has evolved over time?",
		"Can you give an example of how you have motivated a team to achieve a goal?",
		"Can you describe a time when you had to make a difficult decision as a leader?",
		"Can you give an example of how you have provided feedback and coaching to a team member to improve their performance?",
		"Can you walk me through how you would lead a team on a new project?",
		"Can you describe a time when you had to work with a difficult colleague or stakeholder? How did you handle the situation?",
		"Can you give an example of how you have built relationships with colleagues or customers?",
		"How do you handle conflicts or misunderstandings with colleagues or superiors?",
		"Can you describe a time when you had to collaborate with someone who had a different working style than you?",
		"Can you walk me through a time when you had to work with a team to achieve a goal?",
		"Can you give an example of how you have adapted to a change in a work environment or process?",
		"Can you describe a time when you had to change your approach to a project or task midway through?",
		"Can you walk me through a time when you had to prioritize competing tasks or responsibilities?",
		"Can you give an example of how you have handled a situation where priorities or deadlines shifted unexpectedly?",
		"How do you stay organized and focused when faced with unexpected challenges or changes?",
		"Can you describe your process for managing your time and tasks?",
		"How do you prioritize tasks when you have multiple competing responsibilities?",
		"Can you give an example of how you have successfully managed a project with multiple deadlines?",
		"Can you describe a time when you had to make a trade-off between quality and speed in your work?",
		"How do you handle interruptions or unexpected demands on your time?",
		"Can you give an example of a time when you came up with a creative solution to a problem in your previous work experience?",
		"How do you incorporate new and innovative ideas into your work processes?",
		"Can you describe a project or initiative that you led which involved creative thinking and innovation?",
		"What steps do you take to foster creativity and innovation in your team or colleagues?",
		"How do you stay up-to-date with new industry trends and incorporate them into your work?",
		"How do you handle stressful situations in the workplace and maintain your composure?",
		"Can you give an example of a time when you had to manage a difficult situation with a colleague or customer and how you handled it?",
		"How do you handle receiving constructive criticism from others?",
		"Can you describe a time when you had to adapt your communication style to work effectively with someone who had a different personality than your own?",
		"How do you demonstrate empathy and understanding towards others in the workplace?",
		"How do you stay informed of industry changes and trends?",
		"Can you give an example of a new skill or concept that you learned recently and how you applied it to your work?",
		"What steps do you take to continue developing your skills and knowledge in your field?",
		"How do you seek out feedback to continually improve your performance?",
		"Can you describe a time when you took the initiative to learn a new skill or take on a new project outside of your normal responsibilities?",
	],
	contributionQuestions: [
		"Can you tell us about a time when you went above and beyond in your previous job to achieve a goal or complete a project successfully?",
		"In your opinion, what is the most significant contribution you have made in your career so far?",
		"How do you ensure that your contributions align with the goals and objectives of the organization you work for?",
		"Can you describe a project you initiated or led that resulted in a positive outcome for your team or organization?",
		"What skills or qualities do you bring to the table that you think will make a significant contribution to our organization?",
		"How have you helped your previous employer save time, reduce costs, or increase revenue?",
		"Tell us about a time when you identified a problem in your previous job and took the initiative to solve it.",
		"Can you share an example of a situation where you collaborated with others to make a meaningful contribution to a project or task?",
		"How do you measure the success of your contributions? Can you give us an example of how you have done this in the past?",
		"How have you contributed to the growth and development of your team or organization in your previous job?",
		"Can you describe a specific accomplishment you achieved in your previous role that you are most proud of?",
		"How did you approach this accomplishment and what steps did you take to achieve it?",
		"What challenges did you face and how did you overcome them to accomplish this achievement?",
		"Can you provide metrics or data to support the impact of your accomplishment on the organization?",
		"How did your accomplishment benefit your team and the organization as a whole?",
		"Can you describe your leadership style and how it has evolved over time?",
		"Can you provide an example of a situation where you demonstrated leadership and how it impacted your team or organization?",
		"How do you motivate and inspire your team to achieve their goals?",
		"How have you coached or mentored others to develop their own leadership skills?",
		"Can you describe a situation where you had to navigate a difficult leadership challenge and how you addressed it?",
		"Can you describe a time when you introduced a new idea or approach to solve a problem or improve a process in your previous role?",
		"How did you generate this innovative idea and what steps did you take to implement it?",
		"Can you provide examples of how your innovative thinking has benefited your previous organization or team?",
		"How do you encourage and foster innovative thinking within your team or organization?",
		"Can you describe how you have stayed up-to-date with emerging trends and technologies in your field to promote innovative thinking?",
		"Can you describe a project or initiative where you collaborated with others in your previous role?",
		"How did you approach collaboration and what steps did you take to ensure its success?",
		"Can you provide examples of how your collaborative skills have benefited your previous team or organization?",
		"How do you manage conflicts or disagreements within a team or organization when collaborating?",
		"How do you communicate and share information with team members to ensure everyone is on the same page?",
		"Can you describe how you measure the impact of your work and contributions to the organization?",
		"How do you ensure that your work aligns with the organization's goals and mission?",
		"Can you provide examples of how your work and contributions have positively impacted the organization or team?",
		"How do you solicit feedback from colleagues or managers to ensure that you are making a positive impact?",
		"How do you prioritize and manage your workload to ensure maximum impact on the organization?",
		"How do you approach professional development and growth opportunities?",
		"Can you provide examples of how you have pursued growth and development opportunities in your previous roles?",
		"Can you describe how you have used feedback and critiques to improve your skills and performance?",
		"How do you encourage and support the growth and development of your team members?",
		"Can you provide examples of how you have taken on new challenges or responsibilities to expand your skills and knowledge?",
		"Can you describe a time when you took initiative to solve a problem or improve a process in your previous role?",
		"How did you identify the problem or opportunity and what steps did you take to address it?",
		"Can you provide examples of how your initiative has positively impacted your previous team or organization?",
		"How do you encourage and foster initiative within your team or organization?",
		"How do you balance taking initiative with following established procedures and protocols?",
		"Can you describe how you measure the success of your work and contributions to the organization?",
		"Can you provide examples of how you have set and achieved specific goals in your previous roles?",
		"How do you prioritize your workload to ensure you are achieving the most important goals and objectives?",
		"Can you describe how you have balanced short-term and long-term goals in your previous roles?",
		"How do you ensure that your work aligns with the organization's strategic goals?",
		"Can you describe a time when you had to adapt to a new work environment or task, and how did you handle it?",
		"How have you been able to adjust to changes or unexpected situations in your previous work experience?",
		"Can you discuss how you have successfully transitioned from one job role or project to another, and what you did to ensure a smooth transition?",
		"Can you provide an example of how you have modified your approach to work or problem-solving based on feedback or new information?",
		"How have you managed conflicting priorities and competing demands in previous work experiences?",
		"How do you evaluate your own performance and identify areas for improvement?",
		"Can you describe a time when you received constructive feedback and how you responded to it?",
		"How have you pursued personal and professional growth and development through self-reflection and self-assessment?",
		"Can you discuss a mistake or failure you experienced in a previous job, and how you reflected on the experience and used it as a learning opportunity?",
		"How have you demonstrated a willingness to learn and improve through self-reflection and self-evaluation in previous work experiences?",
	],
};
